force-app/main/default/objects/Customer_Feedback__c/Customer_Feedback__c.object-meta.xml
<CustomObject>
    <label>Customer Feedback</label>
    <nameField>
        <displayFormat>CF-{0000}</displayFormat>
        <label>Feedback ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Feedback__c/fields/Customer_Email__c.field-meta.xml
<CustomField>
    <fullName>Customer_Email__c</fullName>
    <label>Customer Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Customer_Feedback__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <label>Customer Name</label>
    <type>Text</type>
    <length>80</length>
</CustomField>

force-app/main/default/classes/EmailFeedbackNotifier.cls
public class EmailFeedbackNotifier implements IFeedbackNotifier {
    public void notifyOnNewFeedback(List<Customer_Feedback__c> newRecords) {
        List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
        for (Customer_Feedback__c fb : newRecords) {
            Messaging.SingleEmailMessage msg = new Messaging.SingleEmailMessage();
            msg.setToAddresses(new String[]{ fb.Customer_Email__c });
            msg.setSubject('Thank you for your feedback');
            msg.setHtmlBody(
                'Hi ' + fb.Customer_Name__c + ',<br/><br/>' +
                'Thanks for submitting: ' + fb.Description__c + '<br/><br/>' +
                'We appreciate your input!'
            );
            mails.add(msg);
        }
        if (!mails.isEmpty()) {
            Messaging.sendEmail(mails);
        }
    }
} 